### ISSUE TITLE
Discuss storage options for bud burst data

### ISSUE THREAD

**Issue by StefanVriend** [LTER-LIFE/VeluweProtoDT#10]
The bud burst data collected by Animal Ecology/NIOO-KNAW are currently stored on NIOO's server. However, we want to access the data inputs in our workflow from open and accessible repositories (e.g., through an API) rather than loading files from a local drive or server.

**Comment by StefanVriend** [comment]
Ideally within LTER-LIFE's infrastructure, data exist in a single copy at a single location (i.e., with the data holder or at another institution's repository; e.g., DANS) and accessible in LTER-LIFE through APIs. This way, we ensure secure access to data and refrain from circulating various versions of a single dataset.

However, NIOO's systems are not (yet) ready for external access through APIs, so we will have to come up with an intermediary solution. We will discuss with Eric Kuijt, NIOO's data steward, what options we have for storing the bud burst data.

**Comment by CherineJ** [comment]
## Decision: Dataverse Demo

### Explanation
We decided together with Eric that, at least for now, the data shall be made available through the demo version of [dataverse](https://demo.dataverse.nl/), from where it can be obtained directly through the dataverse [API](https://guides.dataverse.org/en/latest/api/search.html).

For the purpose of demonstrating the complete workflow of the proto-DT, we decided together with Marcel, that the original data will be stored and that mapping the original data to Darwin Core is part of the demonstrated workflow. 

The original data is however reduced by all columns that contain personal data, because that is not yet anonymised (see #3).
