### ISSUE TITLE
Choose best suited KNMI API

### ISSUE THREAD

**Issue by CherineJ** [LTER-LIFE/VeluweProtoDT#2]
The KNMI offers two different APIs ([Open API](https://developer.dataplatform.knmi.nl/open-data-api) and [EDR API](https://developer.dataplatform.knmi.nl/edr-api)). From the Open API daily temperature data can be downloaded as single netCDF files (one per day) for the whole Netherlands and Rijksdriehoekscoördinaten ([EPSG:28992](https://epsg.io/28992)) are used. The EDR API allows to only query temperature data for a defined time period and geographic bounding box ([EPSG:4326](https://epsg.io/4326)) and provides data directly through R without downloading separate data files. Both APIs are limited in the number of requests than can be done at once. It needs to be decided which API to use.

**Comment by StefanVriend** [comment]
### EDR API
#### Advantages
- relatively quick
- no need to download files
- directly select geographic bounding box
- select time period more straightforwardly
- favourable coordinate system (i.e., EPSG:4326)

#### Disadvantages
- query syntax is not straightforward
- need for splitting data in periods because of request limitations
- data structure unclear
- not completely stable (if larger amounts of data are queried, random errors for some periods occur & data cannot be obtained)

### Open Data API
#### Advantages
- data more easily accessible (because netCDF)
- has bulk API key

#### Disadvantages
- relatively slow
- single-date files all locally downloaded
- unfavourable coordinate system (i.e., EPSG:28992)
- file name changes not traceable (e.g., before 2018 files end with "0005.nc"; afterwards with "0006.nc")

**Comment by StefanVriend** [comment]
## Decision: EDR API

### Explanation
Weighing the advantages and disadvantages of the two APIs (see previous comment), this workflow seems to work best with the EDR API. It is relatively quick, queryable, and does not require any coordinate transformations.
